import Link from 'next/link'
import Navbar from '@/app/ui/navbar'

export const metadata = {
  title: 'Terms of Service — Replyfier',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      <main className="mx-auto max-w-2xl px-6 pt-28 pb-24">
        <Link href="/" className="mb-8 inline-flex items-center gap-1.5 text-sm text-slate-400 transition hover:text-slate-700">
          <svg className="h-3.5 w-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M15 19l-7-7 7-7" />
          </svg>
          Back to home
        </Link>

        <h1 className="mb-2 text-3xl font-bold tracking-tight text-slate-900">Terms of Service</h1>
        <p className="mb-10 text-sm text-slate-400">Last updated: May 2026</p>

        <div className="space-y-8 text-[15px] leading-relaxed text-slate-600">

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">1. The service</h2>
            <p>
              Replyfier provides AI-generated reply suggestions for Google Business reviews.
              By creating an account you agree to these Terms of Service. These terms are governed
              by the laws of Denmark and the EU GDPR.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">2. Trial and pricing</h2>
            <p className="mb-2">
              New accounts include a <strong>7-day free trial</strong> with full access to all features.
              No credit card is required during the trial. At the end of the trial you may choose a plan:
            </p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li><strong>Starter — $29/month:</strong> 1 location, 100 replies per month.</li>
              <li><strong>Pro — $59/month:</strong> up to 5 locations, unlimited replies, brand tone per location, priority support.</li>
            </ul>
            <p className="mt-3">
              Subscriptions are billed monthly in advance. Prices are in USD and exclude any applicable taxes.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">3. Cancellation</h2>
            <p>
              You may cancel your subscription at any time from your account settings. Cancellation takes
              effect at the end of the current billing period — you retain full access until then.
              We do not offer refunds for partial periods.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">4. Acceptable use</h2>
            <p className="mb-2">You agree not to use Replyfier to:</p>
            <ul className="list-disc space-y-1.5 pl-5">
              <li>Generate or post fake, misleading, or fraudulent reviews.</li>
              <li>Send spam or unsolicited messages to reviewers.</li>
              <li>Violate Google's terms of service or review policies.</li>
              <li>Harass, threaten, or defame any individual.</li>
              <li>Use the service in any way that breaches applicable law.</li>
            </ul>
            <p className="mt-3">
              We reserve the right to suspend or terminate accounts that violate these rules without notice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">5. AI-generated content and liability</h2>
            <p>
              Replies generated by Replyfier are <strong>suggestions only</strong>. You are solely responsible
              for reviewing, editing, and deciding whether to publish any reply on Google or any other platform.
              Replyfier is not liable for the content of published replies, any responses from reviewers,
              or any impact on your business reputation.
            </p>
            <p className="mt-3">
              To the maximum extent permitted by law, Replyfier's liability for any claim arising out of
              or related to the service is limited to the amount you paid in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">6. Intellectual property</h2>
            <p>
              You retain ownership of any review text and business content you provide.
              You grant Replyfier a limited licence to process that content solely for the purpose
              of generating reply suggestions. Replyfier retains all rights to the platform, software,
              and underlying technology.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">7. Changes to these terms</h2>
            <p>
              We may update these Terms from time to time. If we make material changes we will notify
              you by email at least 14 days before the changes take effect. Continued use of the service
              after that date constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">8. Governing law</h2>
            <p>
              These Terms are governed by the laws of Denmark. Disputes will be resolved in the competent
              courts of Denmark. EU consumers retain any rights granted under mandatory consumer protection
              legislation in their country of residence.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-slate-900">9. Contact</h2>
            <p>
              Questions about these Terms? Email us at{' '}
              <a href="mailto:support@replyfier.com" className="text-blue-600 hover:underline">support@replyfier.com</a>.
            </p>
          </section>

        </div>
      </main>

      <footer className="pb-10 text-center text-xs text-slate-400">
        Replyfier · <Link href="/privacy" className="hover:text-slate-600">Privacy</Link>
        {' · '}
        <Link href="/terms" className="hover:text-slate-600">Terms</Link>
      </footer>
    </div>
  )
}
